services:
  - type: web
    name: servicio-social
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 16.x
